package com.sergio;

import java.security.SecureRandom;

public class Recipient {
    //These are the values that the recipient of the commitment is going to know at one point or another
    private int r, c;//r is generated by the recipient, the other values are sent by the committer
    private byte[] s;
    private boolean b;

    private SecureRandom rand;//Recipient's PRG

    public Recipient() {
        rand = new SecureRandom();
    }

    public int genR(){//Generate R value, 1st step
        r= rand.nextInt();
        return r;
    }

    public void setC(int c) {
        this.c = c;
    }

    public void setS(byte[] s) {
        this.s = s;
    }

    public void setB(boolean b) {
        this.b = b;
    }

    public boolean checkCommit(){
        return c==Commitment.commit(s,r,b);
    }
}
